language: python
sudo: false

cache: pip

python:
  - "3.5"

branches:
  only:
    - master

env:
  matrix:
   - ''  # main tests
   - SAMPLE_APP=1  # sample app tests

before_install:
  - pip install --no-cache-dir -U -r requirements-test.txt
  - ./runflake8
  - ./runisort
  - npm install -g jslint
  - jslint ./django_ipam/static/django-ipam/js/*.js

install:
  - pip install "django>=2.0,<2.1"
  - python setup.py -q develop

before_script:
  - |
    if [[ $TRAVIS_PYTHON_VERSION == 3.5 && $SAMPLE_APP != "1" ]]; then
      OUTPUT=$(./tests/manage.py makemigrations --dry-run django_ipam)
      echo $OUTPUT
      echo $OUTPUT | grep "No changes detected"
    fi

# command to run tests, e.g. python setup.py test
script:
  - coverage run --source=django_ipam runtests.py

after_success:
  - coveralls
